image: node:lts-slim

.shared_rules:
  variables:
    ENV: "STAGING"
  rules:
    - if: ('$CI_COMMIT_BRANCH == "main"' || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")
      variables:
        ENV: "PRODUCTION"
      when: always

stages:
  - lint
  - audit
  - build
  - deploy

include:
  - local: '/.gitlab-ci/Jobs/lint.yml'
  - local: '/.gitlab-ci/Jobs/audit.yml'
  - local: '/.gitlab-ci/Jobs/build.yml'
  - local: '/.gitlab-ci/Jobs/deploy.yml'
