image: node:lts-slim

stages:
  - lint
  - audit
  - build
  - deploy

include:
  - local: '/.gitlab-ci/Jobs/lint.yml'
  - local: '/.gitlab-ci/Jobs/audit.yml'
  - local: '/.gitlab-ci/Jobs/build.yml'
  - local: '/.gitlab-ci/Jobs/deploy.yml'
