.audit:
  stage: audit
  image: node:20
  script:
    - npm ci --include=dev
    - npm audit
    - npm run lint:lockfile
  rules:
    - if: '($CI_PIPELINE_SOURCE == "schedule" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $TARGET_BRANCH )'
      when: on_success

audit-staging:
  extends: .audit
  variables:
    TARGET_BRANCH: develop

audit-production:
  extends: .audit
  variables:
    TARGET_BRANCH: main
